#!/bin/bash

cat << 'EOF'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🧠 MANDATORY MEMORY EVALUATION REQUIRED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After completing this request, evaluate whether it produced
extractable knowledge or decisions worth saving to memory.

LEARNINGS → Non-obvious debugging, workarounds, error resolutions
  Save as: learning_<topic>_<specific>

DECISIONS → Architecture choices, conventions, preferences, tool selections
  Save as: decision_<domain>_<topic>

If YES to either → Use Skill(continuous-learning) to extract and save.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
